<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
    <NoWarn>1701;1702;1591;CS8618;</NoWarn>
  </PropertyGroup>

<!-- strange, why doesn't work -->
<!--  <ItemGroup>-->
<!--    <EmbeddedResource Include=".\ProcessEngine\Definitions\Flows\**\*.json">-->
<!--      <Link>ProcessEngine\Definitions\Flows\%(RecursiveDir)%(Filename)%(Extension)</Link>-->
<!--    </EmbeddedResource>-->
<!--    <EmbeddedResource Include=".\ProcessEngine\Definitions\Templates\**\*.*">-->
<!--      <Link>ProcessEngine\Definitions\Templates\%(RecursiveDir)%(Filename)%(Extension)</Link>-->
<!--    </EmbeddedResource>-->
<!--  </ItemGroup>-->

  <ItemGroup>
    <None Remove="ProcessEngine\Definitions\Flows\**\*.json" />
    <Content Remove="ProcessEngine\Definitions\Flows\**\*.json" />
    <None Remove="ProcessEngine\Definitions\Templates\**\*.*" />
    <Content Remove="ProcessEngine\Definitions\Templates\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ProcessEngine\Definitions\Flows\**\*">
      <LogicalName>$(RootNamespace).ProcessEngine.Definitions.Flows.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ProcessEngine\Definitions\Templates\**\*.*">
      <LogicalName>$(RootNamespace).ProcessEngine.Definitions.Templates.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
      <WithCulture>false</WithCulture>  <!-- IMPORTANT -->
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <CrossErrorHandlersVersion>7.6.0</CrossErrorHandlersVersion>
    <CrossMessagingVersion>2.1.0</CrossMessagingVersion>
    <CrossPepperVaultVersion>1.2.0</CrossPepperVaultVersion>
    <KonsciousSecurityCryptographyArgon2Version>1.3.1</KonsciousSecurityCryptographyArgon2Version>
    <PhoneNumbersCoreVersion>1.1.1</PhoneNumbersCoreVersion>
    <MicrosoftIdentityModelJsonWebTokensVersion>8.16.0</MicrosoftIdentityModelJsonWebTokensVersion>
    <MicrosoftEntityFrameworkCoreVersion>8.0.8</MicrosoftEntityFrameworkCoreVersion>
    <MicrosoftEntityFrameworkCoreVersionInMemory>8.0.8</MicrosoftEntityFrameworkCoreVersionInMemory>
    <MicrosoftEntityFrameworkCoreVersionRelational>8.0.8</MicrosoftEntityFrameworkCoreVersionRelational>
    <MicrosoftExtensionsHttpVersion>8.0.1</MicrosoftExtensionsHttpVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <CrossErrorHandlersVersion>7.6.0</CrossErrorHandlersVersion>
    <CrossMessagingVersion>2.1.0</CrossMessagingVersion>
    <CrossPepperVaultVersion>1.2.0</CrossPepperVaultVersion>
    <KonsciousSecurityCryptographyArgon2Version>1.3.1</KonsciousSecurityCryptographyArgon2Version>
    <PhoneNumbersCoreVersion>1.1.1</PhoneNumbersCoreVersion>
    <MicrosoftIdentityModelJsonWebTokensVersion>8.16.0</MicrosoftIdentityModelJsonWebTokensVersion>
    <MicrosoftEntityFrameworkCoreVersion>9.0.9</MicrosoftEntityFrameworkCoreVersion>
    <MicrosoftEntityFrameworkCoreVersionInMemory>9.0.9</MicrosoftEntityFrameworkCoreVersionInMemory>
    <MicrosoftEntityFrameworkCoreVersionRelational>9.0.9</MicrosoftEntityFrameworkCoreVersionRelational>
    <MicrosoftExtensionsHttpVersion>9.0.15</MicrosoftExtensionsHttpVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <CrossErrorHandlersVersion>7.6.0</CrossErrorHandlersVersion>
    <CrossMessagingVersion>2.1.0</CrossMessagingVersion>
    <CrossPepperVaultVersion>1.2.0</CrossPepperVaultVersion>
    <KonsciousSecurityCryptographyArgon2Version>1.3.1</KonsciousSecurityCryptographyArgon2Version>
    <PhoneNumbersCoreVersion>1.1.1</PhoneNumbersCoreVersion>
    <MicrosoftIdentityModelJsonWebTokensVersion>8.16.0</MicrosoftIdentityModelJsonWebTokensVersion>
    <MicrosoftEntityFrameworkCoreVersion>10.0.9</MicrosoftEntityFrameworkCoreVersion>
    <MicrosoftEntityFrameworkCoreVersionInMemory>10.0.9</MicrosoftEntityFrameworkCoreVersionInMemory>
    <MicrosoftEntityFrameworkCoreVersionRelational>10.0.9</MicrosoftEntityFrameworkCoreVersionRelational>
    <MicrosoftExtensionsHttpVersion>10.0.9</MicrosoftExtensionsHttpVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cross.ErrorHandlers" Version="$(CrossErrorHandlersVersion)" />
    <PackageReference Include="Cross.Messaging" Version="$(CrossMessagingVersion)" />
    <PackageReference Include="Cross.PepperVault" Version="$(CrossPepperVaultVersion)" />

    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="$(KonsciousSecurityCryptographyArgon2Version)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(MicrosoftEntityFrameworkCoreVersionInMemory)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(MicrosoftEntityFrameworkCoreVersionRelational)" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="$(MicrosoftExtensionsHttpVersion)" />
    <PackageReference Include="PhoneNumbersCore" Version="$(PhoneNumbersCoreVersion)" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="$(MicrosoftIdentityModelJsonWebTokensVersion)" />
  </ItemGroup>

</Project>
